spring.application.name=ifsp-projeto-extensao

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/db_tcc?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate Setup for PoC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Disable Flyway temporarily for the PoC to prevent missing migration errors
spring.flyway.enabled=false